use updated brew cask command
```bash
brew cask install blurred
Error: `brew cask` is no longer a `brew` command. Use `brew <command> --cask` instead.
```

So we need to use: `brew install --cask blurred` instead. and it works, and pulls from https://github.com/dwarvesf/blurred/releases/download/...